# Site settings
title: Matemáticas y algo más
description: Un sitio de encuentro entre las mátematicas y el conocimiento en general.
keywords: Modern, Blogging, Fun
author: Wferr
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
